### ISSUE TITLE
Feature request: Attribute to skip some properties of an object

### ISSUE THREAD

**Issue by gigios** [sinairv/YAXLib#49]
I have checked the class but I don't have found an attribute that allow to skip the serialization of some properties in a class.
I try to explain my problem.
I need to serialize a property of type System.Drawing.Size, and the lib works perfectly, but in the serialized file I have also the property IsEmpty that is not necessary.
Could be possible to skip this serialization?
Could be interesting to have an attribute that allow to define a list of properties to ignore during the serialization (necessary for classes/structures standard or from external assemblies)
For example (example to skip IsEmpty and Height properties)
[YAXSkipProperties("IsEmpty;Height")] 

I don't know if this is possible without make a custom serializer
Thanks for any answer

**Comment by sinairv** [comment]
Hi,
You can use the `[YAXDontSerialize]` attribute in the types that you define in your code. But you don't have such control over types within the .NET Framework or types from 3rd party libraries. So if this is a type you have in your code use the above attribute on properties/fields you want to skip, otherwise you need to use a custom serializer.

I hope it helps.

**Comment by gigios** [comment]
Ok! Thanks for the answer :)
