### ISSUE TITLE
Is there a simple way to make a property value to appear as element name?

### ISSUE THREAD

**Issue by douglasgdy** [sinairv/YAXLib#89]
For example, I have a class as follows:
```
public class Person
{
    public string SSN { get; set; } = "SSN-Value";

    [YAXAttributeForClass]
    public string Name { get; set; } = "Name-Value";
}
```

I hope that can be serialized to:
`<SSN-Value Name="Name-Value" />`

**Comment by acvanzant** [comment]
You're asking to have a dynamic value as the tag itself? That would mean the schema itself changes depending on the data. XML doesn't work that way.

However, you can use any arbitrary tag defined ahead of time but it must not depend upon the data.

You could use the YAXValueFor attribute in the containing object instead of creating a Person class.
```
public Record 
{   
   [YAXSerializeAs("SSN-Value")]
   public PersonSSN {get;set;} = "XXX-XX-XXXX";

   [YAXValueForAttribute("SSN-Value#Name")]
   public PersonName {get;set;} = "Guys Name";
}
```
outputs
`<SSN-Value Name="Guys Name">XXX-XX-XXXX</SSN-Value>`

**Comment by douglasgdy** [comment]
@acvanzant Thank you for answer.
